{% set name = "skforecast" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/skforecast-{{ version }}.tar.gz
  sha256: a5bb7f3628c3d79895fda8f6c43e384f446bcf6704323313409773e0d300e322

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - toml
    - python-build
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.24
    - pandas >=1.5
    - tqdm >=4.57
    - scikit-learn >=1.2
    - optuna >=2.10
    - joblib >=1.1
    - numba >=0.59
    - rich >=13.9

test:
  imports:
    - skforecast
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://skforecast.org
  summary: Skforecast is a Python library for time series forecasting using machine learning models. It works with any regressor compatible with the scikit-learn API, including popular options like LightGBM, XGBoost, CatBoost, Keras, and many others.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/skforecast/skforecast

extra:
  recipe-maintainers:
    - JoaquinAmatRodrigo
    - JavierEscobarOrtiz
